apiVersion: apps/v1

kind: Deployment
metadata: 
  name: server-deployment
spec:
  selector:
    matchLabels:
      component: server
  replicas: 1
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: mosabami/multi-server:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value:  redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres@awesonepost
            - name: PGHOST
              value: privatelink.postgres.database.azure.com
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: pgpassword
                  key: PGPASSWORD

