apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-premium-sc